-------------------------------------------------------------------------------
Test set: dao.Sql2oDepartmentsDaoTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.004 sec <<< FAILURE! - in dao.Sql2oDepartmentsDaoTest
dao.Sql2oDepartmentsDaoTest  Time elapsed: 0.003 sec  <<< ERROR!
org.sql2o.Sql2oException: Could not acquire a connection from DataSource - FATAL: password authentication failed for user "adwesh"
	at dao.Sql2oDepartmentsDaoTest.setUp(Sql2oDepartmentsDaoTest.java:23)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "adwesh"
	at dao.Sql2oDepartmentsDaoTest.setUp(Sql2oDepartmentsDaoTest.java:23)

dao.Sql2oDepartmentsDaoTest  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.NullPointerException
	at dao.Sql2oDepartmentsDaoTest.shutDown(Sql2oDepartmentsDaoTest.java:39)

